#pragma once
#include "DuiPanel.h"
#include "control/DuiCmnCtrl.h"
#include "control/DuiCaption.h"
#include "control/duirealwnd.h"
#include "control/duitabctrl.h"
#include "control/DuiActiveX.h"
#include "control/DuiSliderBar.h"
#include "control/DuiSplitWnd.h"
/*
#include "control/duiscrollbar.h"
#include "control/duilistbox.h"
#include "control/duilistboxex.h"
#include "control/duiitembox.h"
#include "control/duitreebox.h"
#include "control/DuiTreeCtrl.h"
#include "control/DuiRichEdit.h"
#include "control/DuiComboBox.h"
#include "control/DuiHotKeyCtrl.h"
#include "control/DuiDateTimeEdit.h"
#include "control/DuiCalendar.h"
#include "control/DuiHeaderCtrl.h"
#include "control/DuiListCtrl.h"
*/