######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 19:29:15 2014
######################################################################

TEMPLATE = lib
TARGET = coll-mem
INCLUDEPATH += .

dir = ..
include($$dir/common.pri)

!CONFIG(LIB_ALL){
	DEFINES += COLLMEM_EXPORTS
}
else{
    CONFIG += staticlib
}

# Input
HEADERS += coll-mem.h 
SOURCES += coll-mem.cpp