#pragma once
// Start of SOUI namespace section
namespace SOUI
{
    class SWindow;

/*!
\brief
    Base class used as the argument to all subscribers Event object.

    The base EventArgs class does not contain any useful information, it is intended
    to be specialised for each type of event that can be generated by objects within
    the system.  The use of this base class allows all event subscribers to have the
    same function signature.

    The \a handled field is used to signal whether an event was actually handled or not.  While
    the event system does not look at this value, code at a higher level can use it to determine
    how far to propagate an event.
*/
class EventArgs
{
public:
    /*************************************************************************
        Construction
    *************************************************************************/
    EventArgs(SWindow *pSender) 
        : handled(0)
        , sender(pSender)
    {}
    virtual ~EventArgs(void) {}
    virtual UINT GetEventID()= 0;
    
    /*************************************************************************
        Data members
    *************************************************************************/
    //! handlers should increment this if they handled the event.
    UINT handled;
    
    SWindow *sender;
};

enum SOUI_EVENTS
{
    EVT_CMD=100,
    EVT_CTXMENU,
    EVT_SCROLL,
    EVT_OFEVENT,
    
    EVT_TAB_SELCHANGING,
    EVT_TAB_SELCHANGED,
    
    EVT_LB_GETDISPINFO,
    EVT_LB_SELCHANGING,
    EVT_LB_SELCHANGED,
    
    EVT_TB_GETDISPINFO,
    EVT_TB_SELCHANGING,
    EVT_TB_SELCHANGED,
    
    EVT_RE_NOTIFY,
    
    EVT_SLIDER_POS,
    
    EVT_HEADER_CLICK,
    EVT_HEADER_ITEMCHANGING,
    EVT_HEADER_ITEMCHANGED,
    EVT_HEADER_ITEMSWAP,

    EVT_CB_SELCHANGE,
    
    EVT_CALENDAR_SELDAY,
};

class EventCmd : public EventArgs
{
public:
    EventCmd(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_CMD};
    virtual UINT GetEventID(){return EventID;}
};

class EventCtxMenu : public EventArgs
{
public:
    EventCtxMenu(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_CTXMENU};
    virtual UINT GetEventID(){return EventID;}
    POINT           pt;
};


class EventScroll : public EventArgs
{
public:
    EventScroll(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_SCROLL};
    virtual UINT GetEventID(){return EventID;}
    UINT        uSbCode;
    int         nPos;
    BOOL        bVertical;
};

class EventOfEvent : public EventArgs
{
public:
    EventOfEvent(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_OFEVENT};
    virtual UINT GetEventID(){return EventID;}
    EventArgs * pOrgEvt;
};

class EventTabSelChanging : public EventArgs
{
public:
    EventTabSelChanging(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_TAB_SELCHANGING};
    virtual UINT GetEventID(){return EventID;}
    UINT        uOldSel;
    UINT        uNewSel;
    BOOL        bCancel;
};

class EventTabSelChanged : public EventArgs
{
public:
    EventTabSelChanged(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_TAB_SELCHANGED};
    virtual UINT GetEventID(){return EventID;}
    UINT        uOldSel;
    UINT        uNewSel;
};

class EventLBGetDispInfo : public EventArgs
{
public:
    EventLBGetDispInfo(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_LB_GETDISPINFO};
    virtual UINT GetEventID(){return EventID;}
    int  iItem;
    SWindow * pItem;
    UINT uState;
};

class EventLBSelChanging : public EventArgs
{
public:
    EventLBSelChanging(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_LB_SELCHANGING};
    virtual UINT GetEventID(){return EventID;}
    int nNewSel;
    int nOldSel;
    BOOL bCancel;
};

class EventLBSelChanged : public EventArgs
{
public:
    EventLBSelChanged(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_LB_SELCHANGED};
    virtual UINT GetEventID(){return EventID;}
    int nNewSel;
    int nOldSel;
};

class EventTBGetDispInfo : public EventArgs
{
public:
    EventTBGetDispInfo(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_TB_GETDISPINFO};
    virtual UINT GetEventID(){return EventID;}
    HSTREEITEM  hItem;
    SWindow     *pItemWnd;
    UINT        uState;
};

class EventTBSelChanging: public EventArgs
{
public:
    EventTBSelChanging(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_TB_SELCHANGING};
    virtual UINT GetEventID(){return EventID;}
    HSTREEITEM hNewSel;
    HSTREEITEM hOldSel;
    BOOL        bCancel;
};

class EventTBSelChanged: public EventArgs
{
public:
    EventTBSelChanged(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_TB_SELCHANGED};
    virtual UINT GetEventID(){return EventID;}
    HSTREEITEM hNewSel;
    HSTREEITEM hOldSel;
};

class EventRENotify : public EventArgs
{
public:
    EventRENotify(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_RE_NOTIFY};
    virtual UINT GetEventID(){return EventID;}
    DWORD iNotify;
    LPVOID pv;
};

class EventSliderPos : public EventArgs
{
public:
    EventSliderPos(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_SLIDER_POS};
    virtual UINT GetEventID(){return EventID;}
    int     nPos;
};

//点击表头
class EventHeaderClick : public EventArgs
{
public:
    EventHeaderClick(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_HEADER_CLICK};
    virtual UINT GetEventID(){return EventID;}
    int   iItem;
};

//点击表头
class EventHeaderItemChanging : public EventArgs
{
public:
    EventHeaderItemChanging(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_HEADER_ITEMCHANGING};
    virtual UINT GetEventID(){return EventID;}
    int   iItem;
    int   nWidth;
};

//点击表头
class EventHeaderItemChanged : public EventArgs
{
public:
    EventHeaderItemChanged(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_HEADER_ITEMCHANGED};
    virtual UINT GetEventID(){return EventID;}
    int   iItem;
    int   nWidth;
};

//拖动表项调整位置
class EventHeaderItemSwap : public EventArgs
{
public:
    EventHeaderItemSwap(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_HEADER_ITEMSWAP};
    virtual UINT GetEventID(){return EventID;}
    int   iOldIndex;
    int      iNewIndex;
};

class EventCBSelChnage : public EventArgs
{
public:
    EventCBSelChnage(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_CB_SELCHANGE};
    virtual UINT GetEventID(){return EventID;}
};

class EventCalendarSelDay : public EventArgs
{
public:
    EventCalendarSelDay(SWindow *pWnd):EventArgs(pWnd){}
    enum{EventID=EVT_CALENDAR_SELDAY};
    virtual UINT GetEventID(){return EventID;}
    WORD   wOldDay;
    WORD   wNewDay;
};


} // End of  CEGUI namespace section