######################################################################
# Automatically generated by qmake (3.0) ?? ?? 27 16:03:38 2014
######################################################################

TEMPLATE = lib
TARGET = soui-sys-resource

dir = ..
include($$dir/common.pri)

QMAKE_LFLAGS += /NOENTRY

RC_FILE += soui-sys-resource.rc
