#pragma once
#include "core/SPanel.h"
#include "SCmnCtrl.h"
#include "SCaption.h"
#include "Srealwnd.h"
#include "Stabctrl.h"
#include "SActiveX.h"
#include "SSliderBar.h"
#include "SSplitWnd.h"
#include "STreeCtrl.h"
#include "Sscrollbar.h"
#include "SHeaderCtrl.h"
#include "SListCtrl.h"
#include "Slistbox.h"
#include "SRichEdit.h"
#include "SHotKeyCtrl.h"
#include "Streebox.h"
#include "Slistboxex.h"
#include "SComboBox.h"
#include "SCalendar.h"
#include "SDateTimeEdit.h"
/*
#include "SItembox.h"
*/